<tr>
	<td style='white-space:nowrap;'>
		<a href="<?php echo APPLICATION_URL.'/public/bug/edit/id/'.$this->id;?>">Edit</a> | 
		<a href='<?php echo APPLICATION_URL.'/public/bug/delete/id/'.$this->id;?>'>Delete</a>
	</td>
	<td>
		<?php echo date('m/d/y', $this->date); ?>
	</td>
	<td><?php echo $this->priority; ?></td>
	<td><?php echo $this->status; ?></td>
	<td><?php echo $this->url; ?></td>
	<td><?php echo $this->author; ?></td>
	<td><?php echo $this->description; ?></td>
</tr>
